[general]
live_config_reload = true

[window]
option_as_alt = "Both"

[font]
size = 14.00

[font.normal]
# family = "Space Mono Nerd Font"
family = "Terminess Nerd Font"
style = "Regular"

[font.bold]
# family = "Space Mono Nerd Font"
family = "Terminess Nerd Font"
style = "SemiBold"

[font.italic]
# family = "Space Mono Nerd Font"
family = "Terminess Nerd Font"
style = "Regular"

[font.bold_italic]
# family = "Space Mono Nerd Font"
family = "Terminess Nerd Font"
style = "SemiBold"

[cursor.style]
shape = "Block"
blinking = "On"

[cursor.vi_mode_style]
shape = "Beam"

[keyboard]
bindings = [
	{ key = "}", mods = "Control|shift", action = "increasefontsize" },
	{ key = "{", mods = "Control|Shift", action = "DecreaseFontSize" },
]
